apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ww-gitops
spec:
  chart:
    spec:
      chart: weave-gitops
      sourceRef:
        kind: HelmRepository
        name: ww-gitops
  interval: 1h0m0s
  values:
    adminUser:
      create: true
      username: admin
      passwordHash: $2a$10$MtBduUVj6WvQL918rJxb.uHJ2XX6J9R48Ul.2q5WzCU2f3B1t9F62